<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExpenseExplorer.Application\ExpenseExplorer.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ExpenseExplorer.Api.Tests" />
    </ItemGroup>

</Project>
