// <auto-generated />
using System;
using ExpenseExplorer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseExplorer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseExplorerDbContext))]
    partial class ExpenseExplorerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("expense")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseExplorer.Infrastructure.Persistence.ReceiptItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Item");

                    b.HasIndex("ReceiptId");

                    b.ToTable("receipt_items", "expense", t =>
                        {
                            t.HasCheckConstraint("ck_receipt_items_amount_not_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_receipt_items_category_not_blank", "btrim(category) <> ''");

                            t.HasCheckConstraint("ck_receipt_items_discount_within_amount", "discount >= 0 and discount <= amount");

                            t.HasCheckConstraint("ck_receipt_items_item_not_blank", "btrim(item) <> ''");

                            t.HasCheckConstraint("ck_receipt_items_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ExpenseExplorer.Infrastructure.Persistence.ReceiptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("store");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("Store");

                    b.ToTable("receipts", "expense", t =>
                        {
                            t.HasCheckConstraint("ck_receipts_store_not_blank", "btrim(store) <> ''");
                        });
                });

            modelBuilder.Entity("ExpenseExplorer.Infrastructure.Persistence.ReceiptItemRow", b =>
                {
                    b.HasOne("ExpenseExplorer.Infrastructure.Persistence.ReceiptRow", null)
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseExplorer.Infrastructure.Persistence.ReceiptRow", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
