@ExpenseExplorer.API_HostAddress = http://localhost:5126
@receiptId = {{$uuid}}

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts
Content-Type: application/json

{
  "storeName": "Store",
  "purchaseDate": "2024-03-01"
}

###

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}
Content-Type: application/json

{
  "item": "Item",
  "Category": "General",
  "quantity": 1,
  "unitPrice": 1.56,
  "totalDiscount": null,
  "description": null
}
