//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseExplorer.WebApp.Resources.Components.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Receipt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Receipt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExpenseExplorer.WebApp.Resources.Components.Pages.Receipt", typeof(Receipt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        internal static string Purchase_date {
            get {
                return ResourceManager.GetString("Purchase date", resourceCulture);
            }
        }
        
        internal static string Total_cost {
            get {
                return ResourceManager.GetString("Total cost", resourceCulture);
            }
        }
        
        internal static string Item_name {
            get {
                return ResourceManager.GetString("Item name", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        internal static string Unit_price {
            get {
                return ResourceManager.GetString("Unit price", resourceCulture);
            }
        }
        
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        internal static string Price_before_discount {
            get {
                return ResourceManager.GetString("Price before discount", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Add_item {
            get {
                return ResourceManager.GetString("Add item", resourceCulture);
            }
        }
        
        internal static string Price_after_discount {
            get {
                return ResourceManager.GetString("Price after discount", resourceCulture);
            }
        }
        
        internal static string INVALID_RECEIPT_ID {
            get {
                return ResourceManager.GetString("INVALID_RECEIPT_ID", resourceCulture);
            }
        }
        
        internal static string EMPTY_ITEM_NAME {
            get {
                return ResourceManager.GetString("EMPTY_ITEM_NAME", resourceCulture);
            }
        }
        
        internal static string EMPTY_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_CATEGORY_NAME", resourceCulture);
            }
        }
        
        internal static string INVALID_QUANTITY {
            get {
                return ResourceManager.GetString("INVALID_QUANTITY", resourceCulture);
            }
        }
        
        internal static string INVALID_UNIT_PRICE {
            get {
                return ResourceManager.GetString("INVALID_UNIT_PRICE", resourceCulture);
            }
        }
        
        internal static string INVALID_DISCOUNT {
            get {
                return ResourceManager.GetString("INVALID_DISCOUNT", resourceCulture);
            }
        }
    }
}
