//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseExplorer.WebApp.Resources.Components.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Receipts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Receipts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExpenseExplorer.WebApp.Resources.Components.Pages.Receipts", typeof(Receipts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string _Title {
            get {
                return ResourceManager.GetString("_Title", resourceCulture);
            }
        }
        
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        internal static string Purchase_date {
            get {
                return ResourceManager.GetString("Purchase date", resourceCulture);
            }
        }
        
        internal static string Total_cost {
            get {
                return ResourceManager.GetString("Total cost", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Page_x_of_y__z_items_total_ {
            get {
                return ResourceManager.GetString("Page x of y (z items total)", resourceCulture);
            }
        }
        
        internal static string Items_per_page {
            get {
                return ResourceManager.GetString("Items per page", resourceCulture);
            }
        }
        
        internal static string New_receipt {
            get {
                return ResourceManager.GetString("New receipt", resourceCulture);
            }
        }
        
        internal static string No_receipts_to_display {
            get {
                return ResourceManager.GetString("No receipts to display", resourceCulture);
            }
        }
        
        internal static string INVALID_RECEIPT_ID {
            get {
                return ResourceManager.GetString("INVALID_RECEIPT_ID", resourceCulture);
            }
        }
        
        internal static string PURCHASE_DATE_IN_FUTURE {
            get {
                return ResourceManager.GetString("PURCHASE_DATE_IN_FUTURE", resourceCulture);
            }
        }
        
        internal static string INVALID_PURCHASE_DATE {
            get {
                return ResourceManager.GetString("INVALID_PURCHASE_DATE", resourceCulture);
            }
        }
    }
}
