@ExpenseExplorer.API_HostAddress = https://localhost:7163
@receiptId = 874bf4516eb44b969338e6535cae355c
@purchaseId = 6ca96c9a0bf34273abeae223afbfa330

GET {{ExpenseExplorer.API_HostAddress}}/api/receipts?pageNumber=1&pageSize=10&search=stc&after=2021-10-02&
    before=2021-10-02&minTotal=1&maxTotal=10

###

GET {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}

###

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts
Content-Type: application/json

{
  "storeName": "Walmart",
  "purchaseDate": "2021-10-01"
}

###

PATCH {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}
Content-Type: application/json

{
  "storeName": "Costco",
  "purchaseDate": "2021-10-02"
}

###

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases
Content-Type: application/json

{
  "item": "Milk",
  "Category": "Groceries",
  "quantity": 2,
  "unitPrice": 2.5,
  "totalDiscount": 0.5,
  "description": "2% milk"
}

###

PATCH {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases/{{purchaseId}}
Content-Type: application/json

{
  "item": "Coca Cola",
  "Category": "Treats",
  "quantity": 1,
  "unitPrice": 1.5,
  "totalDiscount": 0,
  "description": "Coke"
}

###

DELETE {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases/{{purchaseId}}

###

DELETE {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}

###

GET {{ExpenseExplorer.API_HostAddress}}/api/stores?pageNumber=1&pageSize=10&search=cos

###

GET {{ExpenseExplorer.API_HostAddress}}/api/items?pageNumber=1&pageSize=10&search=cola

###

GET {{ExpenseExplorer.API_HostAddress}}/api/categories?pageNumber=1&pageSize=10&search=tre

###

GET {{ExpenseExplorer.API_HostAddress}}/api/reports?from=2021-10-01&to=2021-10-31
