@ExpenseExplorer.API_HostAddress = https://localhost:7163
@receiptId = 2ef4858817ba457ebd97fb91892165df
@purchaseId = 10a78662fb5b41a69f65048ca475ce96

GET {{ExpenseExplorer.API_HostAddress}}/api/receipts?pageNumber=1&pageSize=10

###

GET {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}

###

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts
Content-Type: application/json

{
  "storeName": "Store",
  "purchaseDate": "2024-03-01"
}

###

PATCH {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}
Content-Type: application/json

{
  "storeName": "New Store",
  "purchaseDate": "2024-04-01"
}

###

POST {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases
Content-Type: application/json

{
  "item": "Item",
  "Category": "General",
  "quantity": 5,
  "unitPrice": 5.59,
  "totalDiscount": 0.8,
  "description": "Some description"
}

###

PATCH {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases/{{purchaseId}}
Content-Type: application/json

{
  "item": "New Item",
  "Category": "New Category",
  "quantity": 1,
  "unitPrice": 2.59,
  "totalDiscount": 1.8,
  "description": "Some other description"
}

###

DELETE {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}/purchases/{{purchaseId}}

###

DELETE {{ExpenseExplorer.API_HostAddress}}/api/receipts/{{receiptId}}

###

GET {{ExpenseExplorer.API_HostAddress}}/api/stores?pageNumber=1&pageSize=10

###

GET {{ExpenseExplorer.API_HostAddress}}/api/reports?from=2024-03-01&to=2024-03-20
