<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Testcontainers.PostgreSql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ExpenseExplorer.Api\ExpenseExplorer.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Import\*.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
