<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
        <PackageReference Include="MudBlazor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExpenseExplorer.Contracts\ExpenseExplorer.Contracts.csproj" />
    </ItemGroup>

</Project>
