global using System.Diagnostics;
global using ExpenseExplorer.Domain.Facts;
global using ExpenseExplorer.Domain.Receipts.Facts;
global using ExpenseExplorer.Domain.ValueObjects;
global using ExpenseExplorer.Tests.Common.Generators.ComplexTypes;
global using ExpenseExplorer.Tests.Common.Generators.SimpleTypes.Dates;
global using ExpenseExplorer.Tests.Common.Generators.SimpleTypes.Decimals;
global using ExpenseExplorer.Tests.Common.Generators.SimpleTypes.Strings;
global using FluentAssertions;
global using FsCheck.Xunit;
global using Version = ExpenseExplorer.Domain.ValueObjects.Version;
