<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
        <UserSecretsId>0f7c1b14-31e9-454f-a5f4-8ce7f1a6ce1b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ExpenseExplorer.Api\ExpenseExplorer.Api.csproj" />
    </ItemGroup>

</Project>
